{
    "name": "Odoo PS EDI Framework",
    "version": "19.0.2.0.2",
    "license": "OEEL-1",
    "summary": "Gateway between odoo and third party components",
    "category": "Tools",
    "website": "https://www.odoo.com",
    "author": "Odoo PS",
    "depends": ["mail", "edi_audit"],
    "data": [
        "security/edi_base.xml",
        "security/ir.model.access.csv",
        "data/connection.xml",
        "views/res_config_settings_views.xml",
        "views/edi_connection.xml",
        "views/edi_integration.xml",
        "views/edi_synchronization.xml",
    ],
    "auto_install": False,
    "installable": True,
    "cloc_exclude": ["**/*"],
}
