{
    "name": "SFTP Connection for Odoo PS EDI Framework",
    "version": "17.0.1.0.0",
    "license": "OEEL-1",
    "summary": "",
    "category": "Tools",
    "website": "https://www.odoo.com",
    "author": "Odoo PS",
    "depends": ["edi_ftp_connection"],
    "data": ["views/edi_connection.xml"],
    "hidden": True,
    "auto_install": False,
    "installable": True,
    "external_dependencies": {"python": ["paramiko", "pysftp"]},
    "cloc_exclude": ["**/*"],
}
